language: ruby
branches:
  only:
  - master
env:
- secure: "N9hu5GcqFqY167wB3aCEvxPMr4Qf5UDEKWRny01iXK8S/Imw8Xp4ZIpeCMivCrQoQ3We9dWoc+mq0JAcpso1997nn3FJIm95/X5/zldIwUmy/oECEKdjptaNGq+dNGgHwQ+Z5gAzeYATQlv9GeGUcrN3y3ptoFhwM4P12uH9Q9U="
script: ./scripts/build
after_success: ./scripts/deploy
