name: Joseph Mansfield
author: Joseph Mansfield
highlighter: pygments
encoding: UTF-8
exclude: ['README.md']
url: ""
media_url: "/media"
permalink: /:categories/:title.html
excerpt_separator: ""
rss_path: /articles/
environment: development
