name: Joseph Mansfield
author: Joseph Mansfield
highlighter: pygments
encoding: UTF-8
exclude: ['README.md']
url: http://josephmansfield.uk
permalink: /:categories/:title.html
excerpt_seperator: ""
rss_path: /articles/
environment: development
